### ISSUE TITLE
Extension not working with PDF builder

### ISSUE THREAD

**Issue by miketheman** [rhopfer/sphinx-numbered-blocks#1]
Hello!
I found this extension, and have been trying to make it work with a project.

The HTML builder appears to do the job just fine (once I figured out how and where to customize the formatting).

When trying to run the example project through the latexpdf builder, we see this error:

```
$ make latexpdf
sphinx-build -b latex -d _build/doctrees   . _build/latex
Running Sphinx v1.4.4
making output directory...
loading pickled environment... done
WARNING: while setting up extension ?: directive 'figure' is already registered, it will be overridden
building [mo]: targets for 0 po files that are out of date
building [latex]: all documents
updating environment: 0 added, 0 changed, 0 removed
looking for now-outdated files... none found
processing SphinxNumberedBlocksExamples.tex... index chapter1 chapter2
resolving references...

Exception occurred:
  File "/tmp/sphinx-numbered-blocks/ext/numbered_block.py", line 315, in doctree_resolved
    block = blocks[docname][id]
KeyError: u'figure-0'
The full traceback has been saved in /var/folders/r_/gq71n9vx3t5cytn380tp09fw0000gn/T/sphinx-err-M12oGR.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [latexpdf] Error 1
```

Source line: https://github.com/rhopfer/sphinx-numbered-blocks/blob/master/ext/numbered_block.py#L315

It appears that `blocks[docname]` is an empty `{}` when using the pdf builder, but is fully populated in the HTML builder.

Not really sure where to go from here.

The entire traceback is here:
<details>

```
# Sphinx version: 1.4.4
# Python version: 2.7.12 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:
#   updating environment:
#   0 added, 0 changed, 0 removed
#   looking for now-outdated files...
#   none found
#   processing SphinxNumberedBlocksExamples.tex...
#   index
#   chapter1
#   chapter2
#
#   resolving references...
# Loaded extensions:
#   numbered_block (unknown version) from /Users/miketheman/tmp/sphinx-numbered-blocks/ext/numbered_block.pyc
#   sphinx.ext.mathjax (1.4.4) from python-2.7.12/lib/python2.7/site-packages/sphinx/ext/mathjax.pyc
#   alabaster (0.7.8) from python-2.7.12/lib/python2.7/site-packages/alabaster/__init__.pyc
#   sphinx.ext.ifconfig (1.4.4) from python-2.7.12/lib/python2.7/site-packages/sphinx/ext/ifconfig.pyc
Traceback (most recent call last):
  File "python-2.7.12/lib/python2.7/site-packages/sphinx/cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "python-2.7.12/lib/python2.7/site-packages/sphinx/application.py", line 298, in build
    self.builder.build_update()
  File "python-2.7.12/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 246, in build_update
    self.build(['__all__'], to_build)
  File "python-2.7.12/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 322, in build
    self.write(docnames, list(updated_docnames), method)
  File "python-2.7.12/lib/python2.7/site-packages/sphinx/builders/latex.py", line 123, in write
    appendices=((docclass != 'howto') and self.config.latex_appendices or []))
  File "python-2.7.12/lib/python2.7/site-packages/sphinx/builders/latex.py", line 171, in assemble_doctree
    self.env.resolve_references(largetree, indexfile, self)
  File "python-2.7.12/lib/python2.7/site-packages/sphinx/environment.py", line 1552, in resolve_references
    builder.app.emit('doctree-resolved', doctree, fromdocname)
  File "python-2.7.12/lib/python2.7/site-packages/sphinx/application.py", line 552, in emit
    results.append(callback(self, *args))
  File "/tmp/sphinx-numbered-blocks/ext/numbered_block.py", line 315, in doctree_resolved
    block = blocks[docname][id]
KeyError: u'figure-0'
```

</details>

**Comment by miketheman** [comment]
Found the same issue with the `singlehtml` builder - so it's not specific to PDF.

**Comment by rhopfer** [comment]
Sorry, I made it only for HTML documents (it is implicitly written in the first sentence of the documentation). At the moment there is no latex renderer definition in this extension and I have no idea, how to add numbered blocks in latex (maybe using amsthm).
But it is strange it doens't work for singlehtml, I will check this.

**Comment by rhopfer** [comment]
I fixed the issue for singlehtml builder.

**Comment by miketheman** [comment]
Great news, thanks!
I tried it against the example, and indeed it worked.

But when I tried the same against my project, it fails now with the custom block naming scheme.

```
  File ".../exts/numbered_block.py", line 299, in build_labels
    block = blocks[docname][id]
KeyError: u'scenario-0'
```

My blocks are defined with `.. scenario:: .....` and this works in the regular HTML, but not in singlehtml.

**Comment by miketheman** [comment]
The conf.py entry I have is like so:

``` python
numbered_blocks = [
    {'name': 'scenario', 'label-format': 'Scenario C%s', 'reference-format': 'Scenario C%s'},
]
```

**Comment by rhopfer** [comment]
Hm, it works for me. Can you please post a example how you use your `.. scenario::` blocks, so I can test it by my own?

**Comment by miketheman** [comment]
Certainly!

File structure:
- index.rst:

``` rst
.. toctree::

    scenarios/index
```
- scenarios/index.rst:

``` rst
.. toctree::
    :numbered:

    file1
```
- scenarios/file1.rst:
  (Longer, hidden behind collapse)

<details>

``` rst
*********
Scenarios
*********

Cases
=====

.. epigraph::

    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vulputate lacus non congue maximus. Vestibulum in eleifend massa. Morbi dignissim, quam nec finibus convallis, turpis urna fringilla ante, at consequat tellus justo eget urna. Donec sodales enim posuere sem hendrerit, sed convallis mauris tincidunt. 

    -- Origin: Section :ref:`somewhere`

.. figure:: images/scenario1.svg

.. scenario::
    :name: scenario-name

    Donec at magna felis. Nulla et turpis velit. Nullam mauris sem, convallis et convallis eget, congue nec ante. Suspendisse ut finibus ipsum.
```

</details>

**Comment by rhopfer** [comment]
Please try again.

**Comment by miketheman** [comment]
That works Thanks so much!

**Comment by rhopfer** [comment]
You're welcome. Maybe I find some time to add support for latex, but I cannot promise.

**Comment by miketheman** [comment]
Absolutely!

For reference, the current failure with latex is:

``` bash
Exception occurred:
  File
"...python-2.7.12/lib/python2.7/site-packages/sphinx/writers/latex.py",
line 2130, in unknown_visit
    raise NotImplementedError('Unknown node: ' + node.__class__.__name__)
NotImplementedError: Unknown node: numbered_block
```

**Comment by miketheman** [comment]
Closing. Many moons have passed, and Sphinx is already past 7.x, and things work now.
